/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElasticEmail.Api;
using ElasticEmail.Model;
using ElasticEmail.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElasticEmail.Test.Model
{
    /// <summary>
    ///  Class for testing InboundRoute
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InboundRouteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InboundRoute
        //private InboundRoute instance;

        public InboundRouteTests()
        {
            // TODO uncomment below to create an instance of InboundRoute
            //instance = new InboundRoute();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InboundRoute
        /// </summary>
        [Fact]
        public void InboundRouteInstanceTest()
        {
            // TODO uncomment below to test "IsType" InboundRoute
            //Assert.IsType<InboundRoute>(instance);
        }


        /// <summary>
        /// Test the property 'PublicId'
        /// </summary>
        [Fact]
        public void PublicIdTest()
        {
            // TODO unit test for the property 'PublicId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'FilterType'
        /// </summary>
        [Fact]
        public void FilterTypeTest()
        {
            // TODO unit test for the property 'FilterType'
        }
        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }
        /// <summary>
        /// Test the property 'ActionType'
        /// </summary>
        [Fact]
        public void ActionTypeTest()
        {
            // TODO unit test for the property 'ActionType'
        }
        /// <summary>
        /// Test the property 'ActionParameter'
        /// </summary>
        [Fact]
        public void ActionParameterTest()
        {
            // TODO unit test for the property 'ActionParameter'
        }
        /// <summary>
        /// Test the property 'SortOrder'
        /// </summary>
        [Fact]
        public void SortOrderTest()
        {
            // TODO unit test for the property 'SortOrder'
        }

    }

}
