/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a href=\"https://api.elasticemail.com/public/help\">here</a>.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ElasticEmail.Api;
using ElasticEmail.Model;
using ElasticEmail.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ElasticEmail.Test.Model
{
    /// <summary>
    ///  Class for testing NewSmtpCredentials
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewSmtpCredentialsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewSmtpCredentials
        //private NewSmtpCredentials instance;

        public NewSmtpCredentialsTests()
        {
            // TODO uncomment below to create an instance of NewSmtpCredentials
            //instance = new NewSmtpCredentials();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewSmtpCredentials
        /// </summary>
        [Fact]
        public void NewSmtpCredentialsInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewSmtpCredentials
            //Assert.IsType<NewSmtpCredentials>(instance);
        }


        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'AccessLevel'
        /// </summary>
        [Fact]
        public void AccessLevelTest()
        {
            // TODO unit test for the property 'AccessLevel'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DateCreated'
        /// </summary>
        [Fact]
        public void DateCreatedTest()
        {
            // TODO unit test for the property 'DateCreated'
        }
        /// <summary>
        /// Test the property 'LastUse'
        /// </summary>
        [Fact]
        public void LastUseTest()
        {
            // TODO unit test for the property 'LastUse'
        }
        /// <summary>
        /// Test the property 'Expires'
        /// </summary>
        [Fact]
        public void ExpiresTest()
        {
            // TODO unit test for the property 'Expires'
        }
        /// <summary>
        /// Test the property 'RestrictAccessToIPRange'
        /// </summary>
        [Fact]
        public void RestrictAccessToIPRangeTest()
        {
            // TODO unit test for the property 'RestrictAccessToIPRange'
        }

    }

}
