/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ElasticEmail.Client.OpenAPIDateConverter;

namespace ElasticEmail.Model
{
    /// <summary>
    /// Different send options for a Campaign
    /// </summary>
    [DataContract(Name = "CampaignOptions")]
    public partial class CampaignOptions : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets DeliveryOptimization
        /// </summary>
        [DataMember(Name = "DeliveryOptimization", EmitDefaultValue = false)]
        public DeliveryOptimizationType? DeliveryOptimization { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CampaignOptions" /> class.
        /// </summary>
        /// <param name="deliveryOptimization">deliveryOptimization.</param>
        /// <param name="trackOpens">Should the opens be tracked? If no value has been provided, Account&#39;s default setting will be used..</param>
        /// <param name="trackClicks">Should the clicks be tracked? If no value has been provided, Account&#39;s default setting will be used..</param>
        /// <param name="scheduleFor">Date when this Campaign is scheduled to be sent on.</param>
        /// <param name="triggerFrequency">How often (in minutes) to send the campaign.</param>
        /// <param name="triggerCount">How many times send the campaign.</param>
        /// <param name="splitOptions">splitOptions.</param>
        public CampaignOptions(DeliveryOptimizationType? deliveryOptimization = default(DeliveryOptimizationType?), bool? trackOpens = default(bool?), bool? trackClicks = default(bool?), DateTime? scheduleFor = default(DateTime?), double triggerFrequency = default(double), int triggerCount = default(int), SplitOptions splitOptions = default(SplitOptions))
        {
            this.DeliveryOptimization = deliveryOptimization;
            this.TrackOpens = trackOpens;
            this.TrackClicks = trackClicks;
            this.ScheduleFor = scheduleFor;
            this.TriggerFrequency = triggerFrequency;
            this.TriggerCount = triggerCount;
            this.SplitOptions = splitOptions;
        }

        /// <summary>
        /// Should the opens be tracked? If no value has been provided, Account&#39;s default setting will be used.
        /// </summary>
        /// <value>Should the opens be tracked? If no value has been provided, Account&#39;s default setting will be used.</value>
        /// <example>true</example>
        [DataMember(Name = "TrackOpens", EmitDefaultValue = true)]
        public bool? TrackOpens { get; set; }

        /// <summary>
        /// Should the clicks be tracked? If no value has been provided, Account&#39;s default setting will be used.
        /// </summary>
        /// <value>Should the clicks be tracked? If no value has been provided, Account&#39;s default setting will be used.</value>
        /// <example>true</example>
        [DataMember(Name = "TrackClicks", EmitDefaultValue = true)]
        public bool? TrackClicks { get; set; }

        /// <summary>
        /// Date when this Campaign is scheduled to be sent on
        /// </summary>
        /// <value>Date when this Campaign is scheduled to be sent on</value>
        [DataMember(Name = "ScheduleFor", EmitDefaultValue = true)]
        public DateTime? ScheduleFor { get; set; }

        /// <summary>
        /// How often (in minutes) to send the campaign
        /// </summary>
        /// <value>How often (in minutes) to send the campaign</value>
        [DataMember(Name = "TriggerFrequency", EmitDefaultValue = false)]
        public double TriggerFrequency { get; set; }

        /// <summary>
        /// How many times send the campaign
        /// </summary>
        /// <value>How many times send the campaign</value>
        [DataMember(Name = "TriggerCount", EmitDefaultValue = false)]
        public int TriggerCount { get; set; }

        /// <summary>
        /// Gets or Sets SplitOptions
        /// </summary>
        [DataMember(Name = "SplitOptions", EmitDefaultValue = false)]
        public SplitOptions SplitOptions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CampaignOptions {\n");
            sb.Append("  DeliveryOptimization: ").Append(DeliveryOptimization).Append("\n");
            sb.Append("  TrackOpens: ").Append(TrackOpens).Append("\n");
            sb.Append("  TrackClicks: ").Append(TrackClicks).Append("\n");
            sb.Append("  ScheduleFor: ").Append(ScheduleFor).Append("\n");
            sb.Append("  TriggerFrequency: ").Append(TriggerFrequency).Append("\n");
            sb.Append("  TriggerCount: ").Append(TriggerCount).Append("\n");
            sb.Append("  SplitOptions: ").Append(SplitOptions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
