/*
 * Elastic Email REST API
 *
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ElasticEmail.Client.OpenAPIDateConverter;

namespace ElasticEmail.Model
{
    /// <summary>
    /// InboundRoute
    /// </summary>
    [DataContract(Name = "InboundRoute")]
    public partial class InboundRoute : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets FilterType
        /// </summary>
        [DataMember(Name = "FilterType", EmitDefaultValue = false)]
        public InboundRouteFilterType? FilterType { get; set; }

        /// <summary>
        /// Gets or Sets ActionType
        /// </summary>
        [DataMember(Name = "ActionType", EmitDefaultValue = false)]
        public InboundRouteActionType? ActionType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="InboundRoute" /> class.
        /// </summary>
        /// <param name="publicId">publicId.</param>
        /// <param name="name">Name of this route.</param>
        /// <param name="filterType">filterType.</param>
        /// <param name="filter">Filter of the inbound data.</param>
        /// <param name="actionType">actionType.</param>
        /// <param name="actionParameter">URL address or Email to notify about the inbound.</param>
        /// <param name="sortOrder">Place of this route in your routes queue&#39;s order.</param>
        public InboundRoute(string publicId = default(string), string name = default(string), InboundRouteFilterType? filterType = default(InboundRouteFilterType?), string filter = default(string), InboundRouteActionType? actionType = default(InboundRouteActionType?), string actionParameter = default(string), int sortOrder = default(int))
        {
            this.PublicId = publicId;
            this.Name = name;
            this.FilterType = filterType;
            this.Filter = filter;
            this.ActionType = actionType;
            this.ActionParameter = actionParameter;
            this.SortOrder = sortOrder;
        }

        /// <summary>
        /// Gets or Sets PublicId
        /// </summary>
        [DataMember(Name = "PublicId", EmitDefaultValue = false)]
        public string PublicId { get; set; }

        /// <summary>
        /// Name of this route
        /// </summary>
        /// <value>Name of this route</value>
        [DataMember(Name = "Name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Filter of the inbound data
        /// </summary>
        /// <value>Filter of the inbound data</value>
        [DataMember(Name = "Filter", EmitDefaultValue = false)]
        public string Filter { get; set; }

        /// <summary>
        /// URL address or Email to notify about the inbound
        /// </summary>
        /// <value>URL address or Email to notify about the inbound</value>
        [DataMember(Name = "ActionParameter", EmitDefaultValue = false)]
        public string ActionParameter { get; set; }

        /// <summary>
        /// Place of this route in your routes queue&#39;s order
        /// </summary>
        /// <value>Place of this route in your routes queue&#39;s order</value>
        [DataMember(Name = "SortOrder", EmitDefaultValue = false)]
        public int SortOrder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InboundRoute {\n");
            sb.Append("  PublicId: ").Append(PublicId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  FilterType: ").Append(FilterType).Append("\n");
            sb.Append("  Filter: ").Append(Filter).Append("\n");
            sb.Append("  ActionType: ").Append(ActionType).Append("\n");
            sb.Append("  ActionParameter: ").Append(ActionParameter).Append("\n");
            sb.Append("  SortOrder: ").Append(SortOrder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
